Communicating error commit.
Stack trace:

Nov 06, 2014 11:34:36 AM
org.apache.uima.adapter.jms.activemq.SpringContainerDeployer
initializeContainer
WARNING: 
org.apache.uima.resource.ResourceInitializationException: Initialization
of annotator class "gov.va.vinci.vitals.ae.HrVectorAnnotator" failed. 
(Descriptor:
file:/C:/Users/VHASLC~1/AppData/Local/Temp/3/gov.va.vinci.vitals.ae.HrVectorAnnotator2112f595f893-2e91-498e-90fb-80a0cb2c287f226531373764838111.xml)
	at
org.apache.uima.adapter.jms.activemq.SpringContainerDeployer.waitForServiceNotification(SpringContainerDeployer.java:530)
	at
org.apache.uima.adapter.jms.activemq.SpringContainerDeployer.initializeContainer(SpringContainerDeployer.java:314)
	at
org.apache.uima.adapter.jms.activemq.SpringContainerDeployer.deploy(SpringContainerDeployer.java:434)
	at
org.apache.uima.adapter.jms.client.BaseUIMAAsynchronousEngine_impl.deploy(BaseUIMAAsynchronousEngine_impl.java:824)
	at gov.va.vinci.leo.Service.deploy(Service.java:232)
	at gov.va.vinci.leo.Service.deploy(Service.java:203)
	at gov.va.vinci.leo.Service.deploy(Service.java:165)
	at gov.va.vinci.vitals.Service.run(Service.java:172)
	at gov.va.vinci.vitals.Service.main(Service.java:127)
Caused by: org.apache.uima.resource.ResourceInitializationException:
Initialization of annotator class
"gov.va.vinci.vitals.ae.HrVectorAnnotator" failed.  (Descriptor:
file:/C:/Users/VHASLC~1/AppData/Local/Temp/3/gov.va.vinci.vitals.ae.HrVectorAnnotator2112f595f893-2e91-498e-90fb-80a0cb2c287f226531373764838111.xml)
	at
org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:265)
	at
org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:170)
	at
org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at
org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at
org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at
org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
	at
org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
	at
org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:430)
	at
org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:374)
	at
org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:187)
	at
org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at
org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at
org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at
org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
	at
org.apache.uima.aae.controller.PrimitiveAnalysisEngineController_impl.initializeAnalysisEngine(PrimitiveAnalysisEngineController_impl.java:195)
	at
org.apache.uima.aae.UimaAsThreadFactory$1.run(UimaAsThreadFactory.java:119)
	at java.lang.Thread.run(Thread.java:722)
Caused by: org.apache.uima.resource.ResourceInitializationException:
EXCEPTION MESSAGE LOCALIZATION FAILED:
java.util.MissingResourceException: Can't find resource for bundle
java.util.PropertyResourceBundle, key Missing paramater outputType
required!
	at
gov.va.vinci.sherlock.ae.BaseFeatureVectorAnnotator.initialize(BaseFeatureVectorAnnotator.java:93)
	at
org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:263)
	... 16 more

Former-commit-id: 3a111d814048a0f2c8be401ad042ccdbe2fa2daa